name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: self-hosted
    env:
      VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        env:
          CI: true
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-prod

      - name: Package
        run: bash ./scripts/package.sh ${{ env.VERSION }}

      - run: ls

      # - name: Upload assets to release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.release.outputs.upload_url }}
      #     asset_path: /archive/dark-mode-plugin-1.0.0.zip
      #     asset_name: dark-mode-plugin.zip
      #     asset_content_type: application/zip
