name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - name: Install git if missing # Containers used by nektos/act don't have git preinstalled
        run: if ! which git &> /dev/null; then apt-get update && apt-get install -y git; fi; 

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build-prod

      - name: Package
        run: bash ./scripts/package.sh ${{ env.VERSION }}

      - name: Release
        uses: hainguyenvan6799/automation-build-and-release@1.0.0
        id: release

      - name: Show folder
        run: cd archive && ls

      - name: Upload assets to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./archive/dark-mode-plugin-1.0.0.zip
          asset_name: dark-mode-plugin.zip
          asset_content_type: application/zip
